### ISSUE TITLE
Difference to official version?

### ISSUE THREAD

**Issue by Bluejanis** [coderjinhui/pdfjs-ts#1]
Hey, what the difference compared to the officialy maintained type?

[@types/pdfjs-dist](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/pdfjs-dist)

**Comment by coderjinhui** [comment]
> Why I write this package?

Just because I want to write a simple version by typescript.

> What the difference between this package and `@types/pdfjs-dist`?

Emmm... That's because some times the code using `@types/pdfjs-dist` is not really I want...

> And... Why typescript?

Typescript has good code hints... But it is not important, the real reason is that I'm learning typescript, and I want to choose some thing as exercise. It is a good chance to learn typescript and pdf.js core function.

> At last, is it just an exercise project?

No. Although there's only few people use it(maybe no people except me), I'll still working on it if I have time. And thank you for your response, I mean... I quite don't know if any one really use it. I thought there might no people use it expect me. And I'm happy if this package helps you. :)
